euler:
  application:
    runtime-path: /var/lib/${spring.application.name}
    temp-path: /var/tmp/${spring.application.name}
  security:
    app-attest:
      enabled: true
      development-environment: true
