# upstream service-account {
#     server service-account:8080;
# }

# server {
#     listen 80;
# 	server_name account.eulerproject.org;
# 	rewrite ^(.*) https://$host$1 permanent;
# }

server {
    listen 443 ssl;
    http2 on;
    server_name account.eulerproject.org;

    ssl_certificate         /etc/nginx/tls/eulerproject.org/cert.pem;
    ssl_certificate_key     /etc/nginx/tls/eulerproject.org/cert.key;
    ssl_dhparam             /etc/nginx/tls/dhparams.pem;
    ssl_protocols           TLSv1.2 TLSv1.3;
    ssl_ciphers             'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers on;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
    
    access_log  /var/log/nginx/access_account.eulerproject.org.log;
}

