server {
    listen 80 default_server;
    server_name _;
    return 444;
}

server {
    listen 443 ssl default_server;
    http2 on;
    server_name _;

    ssl_certificate         /etc/nginx/tls/eulerproject.org/cert.pem;
    ssl_certificate_key     /etc/nginx/tls/eulerproject.org/cert.key;

    return 444;
}
